---
title: "Digital Behavioral Data"
subtitle: "Winter semester 2023/24"
date: 10/01/2023
date-modified: last-modified
date-format: "DD.MM.YYYY"
author: 
  - name: Christoph Adrian 
    url: /course-team.html
    affiliation: Chair of Communication Science
    affiliation-url: https://www.kowi.rw.fau.de/person/christoph-adrian/
---

::: callout-note
This page contains an outline of the topics, contents, and assignments for the semester. Please note that the contents of the course will be updated as the semester progresses, with all changes documented here.
:::

<!-- FIXME Add column with link to exercises / group activities -->

| Session | Datum          | Topic                             | Prepare                                                                            | Slides                                                                                                                                                                                                                                                                      |
|---------------|---------------|---------------|---------------|---------------|
|         |                | **Introduction**                  |                                                                                    |                                                                                                                                                                                                                                                                             |
| 1       | 25.10.2023     | Kick-Off                          | [{{< bi book >}}](/sessions/session-01.html "Session 01"){aria-label="Session 01"} | [{{< bi file-earmark-slides >}}](/slides/slides-01.html "Slides: Session 01"){aria-label="Slides Session 01"}                                                                                                                                                               |
| \-      | 01.11.2023     | 🎃 *Holiday (No Lecture)*         |                                                                                    |                                                                                                                                                                                                                                                                             |
| 2       | 08.11.2023     | Einführung in DBD                 | [{{< bi book >}}](/sessions/session-02.html "Session 02"){aria-label="Session 02"} | [{{< bi file-earmark-slides >}}](/slides/slides-02.html "Slides: Session 02"){aria-label="Slides Session 02"}                                                                                                                                                               |
| 3       | 15.11.2023     | 🔨 Working with R                 | [{{< bi book >}}](/sessions/session-03.html "Session 03"){aria-label="Session 04"} | [{{< bi file-earmark-slides >}}](/slides/slides-03.html "Slides: Session 03"){aria-label="Slides Session 02"}                                                                                                                                                               |
|         | **🗣️**         | **Presentations**                 |                                                                                    |                                                                                                                                                                                                                                                                             |
| 4       | 22.11.2023     | 📚 Media routines & habits        | [{{< bi book >}}](/sessions/session-04.html "Session 04"){aria-label="Session 04"} | [{{< bi file-earmark](/slides/slides-04.html "Slides: Session 04"){aria-label="Slides Session 02"}[-](/slides/slides-04.html "Slides: Session 03"){aria-label="Slides Session 02"}[slides >}}](/slides/slides-03.html "Slides: Session 03"){aria-label="Slides Session 02"} |
| 5       | 29.11.2023     | 📚 Digital disconnection          | [{{< bi book >}}](/sessions/session-05.html "Session 05"){aria-label="Session 05"} | [{{< bi file-earmark-slides >}}](/slides/slides-05.html "Slides: Session 05"){aria-label="Slides Session 02"}                                                                                                                                                               |
| 6       | 06.12.2023     | 📦 Data collection methods        | [{{< bi book >}}](/sessions/session-06.html "Session 06"){aria-label="Session 09"} |                                                                                                                                                                                                                                                                             |
| 7       | 13.12.2023     | 📦 Automatic text analysis        | [{{< bi book >}}](/sessions/session-07.html "Session 07"){aria-label="Session 09"} |                                                                                                                                                                                                                                                                             |
| 8       | 20.12.2023     | *Buffer Session*                  |                                                                                    |                                                                                                                                                                                                                                                                             |
| \-      | \-             | 🎄*Christmas Break (No Lecture)*  |                                                                                    |                                                                                                                                                                                                                                                                             |
|         | 📂 **Project** | **Analysis of media content**     |                                                                                    |                                                                                                                                                                                                                                                                             |
| 9       | 10.01.2024     | 🔨 Text as data in R              |                                                                                    |                                                                                                                                                                                                                                                                             |
| 10      | 17.01.2024     | 🔨 Topic Modeling in R            |                                                                                    |                                                                                                                                                                                                                                                                             |
| 11      | 24.01.2024     | 🔨 Q&A                            |                                                                                    |                                                                                                                                                                                                                                                                             |
| 12      | 31.01.2024     | 📊 Presentation & Discussion      |                                                                                    |                                                                                                                                                                                                                                                                             |
| 13      | 07.02.2024     | 🏁 Recap, Evaluation & Discussion |                                                                                    |                                                                                                                                                                                                                                                                             |

: {tbl-colwidths="\[2,20,50,5,5,5,5 \]"}

## Copyright

This content is licensed under a [GPL-3.0 License](https://www.gnu.org/licenses/gpl-3.0.en.html).

```{r backup}
#| echo: false
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |

Icons

-   Preparation: {{< bi book >}}
-   Slides: {{< bi file-earmark-slides >}}
-   Group Activity: {{< iconify octicon comment-discussion-24 >}}
-   Application exercises: {{< iconify simple-icons googlecolab >}}