---
title: "📚 Digital disconnection"
subtitle: "Session 04"
date: 29 11 2023
date-format: "DD.MM.YYYY"
filters:
  - roughnotation
  - line-highlight
bibliography: references_slides.bib
---

# 🚧 Under construction {background-image="img/slide_bg-section.png"}

Die Folien werden aktuell überarbeitet, sind aber spätestens zur 3.Sitzung (15.11) online.

```{r under-construction-stop-render}
#| echo: false


knitr::knit_exit()
```

## Seminarplan

```{r setup-slide-session}
#| echo: false

# Load packages
# Load schedule
source(here::here("slides/schedule.R"))

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
    here, taylor,
    magrittr,
    tidyverse, janitor,
    ggpubr, 
    gt, gtExtras,
    countdown
)
```

```{r table-schedule-b}
#| echo: false 

new_schedule_b %>% 
    gt::gt() %>% 
    gt::fmt_markdown() %>% 
    gt::tab_options(
        table.width = gt::pct(75), 
        table.font.size = "12px"
    ) %>% 
    gtExtras::gt_theme_nytimes() %>% 
    # mark session
    gtExtras::gt_highlight_rows(
        rows = 7,
        fill = "#C50F3C", alpha = 0.15,
        bold_target_only = TRUE,
        target_col = Topic
    ) %>%
    # mark past Session
    gt::tab_style(
        style = cell_text(
            style = "italic", 
            color = "grey"),
        location = cells_body(
            columns = everything(), 
            rows = 1:5)
    )
```

# Agenda {background-image="img/slide_bg-agenda.png"}

1.  [Organisation & Koordination](#organisation-koordination)
2.  👥 [Group Activity](#group-activity)
